// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMrO4jKNSNjCRXng3wSBH9qPnyTpzbA9k',
    appId: '1:786469384727:web:dcfb0db64499e55a7e6252',
    messagingSenderId: '786469384727',
    projectId: 'fluttertodoapp-f8b26',
    authDomain: 'fluttertodoapp-f8b26.firebaseapp.com',
    storageBucket: 'fluttertodoapp-f8b26.firebasestorage.app',
    measurementId: 'G-PX4EB7NM4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHTklUvknvmwllX_oOeibIH-t98Q7yKaQ',
    appId: '1:786469384727:android:c26906b5f333a5037e6252',
    messagingSenderId: '786469384727',
    projectId: 'fluttertodoapp-f8b26',
    storageBucket: 'fluttertodoapp-f8b26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsjaPzXhDfQtPL-WFvKuayMLLSNj7StXY',
    appId: '1:786469384727:ios:baf32e411bae57a37e6252',
    messagingSenderId: '786469384727',
    projectId: 'fluttertodoapp-f8b26',
    storageBucket: 'fluttertodoapp-f8b26.firebasestorage.app',
    iosBundleId: 'com.yt.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsjaPzXhDfQtPL-WFvKuayMLLSNj7StXY',
    appId: '1:786469384727:ios:baf32e411bae57a37e6252',
    messagingSenderId: '786469384727',
    projectId: 'fluttertodoapp-f8b26',
    storageBucket: 'fluttertodoapp-f8b26.firebasestorage.app',
    iosBundleId: 'com.yt.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMrO4jKNSNjCRXng3wSBH9qPnyTpzbA9k',
    appId: '1:786469384727:web:8624da38380116f07e6252',
    messagingSenderId: '786469384727',
    projectId: 'fluttertodoapp-f8b26',
    authDomain: 'fluttertodoapp-f8b26.firebaseapp.com',
    storageBucket: 'fluttertodoapp-f8b26.firebasestorage.app',
    measurementId: 'G-C9GMG0TG9B',
  );

}