// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4L2iznoHTLtsrQMvoelnMn4SZL6hsaag',
    appId: '1:635551106785:web:57fb7a7f54702a02c799a0',
    messagingSenderId: '635551106785',
    projectId: 'yttodoapp-1dacb',
    authDomain: 'yttodoapp-1dacb.firebaseapp.com',
    storageBucket: 'yttodoapp-1dacb.firebasestorage.app',
    measurementId: 'G-51FZR5LJGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsm_cdapJUykKxSWpPtk0pdnXUEQ09b7s',
    appId: '1:635551106785:android:8f77a6eb4831b120c799a0',
    messagingSenderId: '635551106785',
    projectId: 'yttodoapp-1dacb',
    storageBucket: 'yttodoapp-1dacb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbmhuao1bdRDEaUSgtR8c92VFpIuIexno',
    appId: '1:635551106785:ios:9a95e37533060fdfc799a0',
    messagingSenderId: '635551106785',
    projectId: 'yttodoapp-1dacb',
    storageBucket: 'yttodoapp-1dacb.firebasestorage.app',
    iosBundleId: 'com.yt.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbmhuao1bdRDEaUSgtR8c92VFpIuIexno',
    appId: '1:635551106785:ios:9a95e37533060fdfc799a0',
    messagingSenderId: '635551106785',
    projectId: 'yttodoapp-1dacb',
    storageBucket: 'yttodoapp-1dacb.firebasestorage.app',
    iosBundleId: 'com.yt.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4L2iznoHTLtsrQMvoelnMn4SZL6hsaag',
    appId: '1:635551106785:web:d03546a475bd52e2c799a0',
    messagingSenderId: '635551106785',
    projectId: 'yttodoapp-1dacb',
    authDomain: 'yttodoapp-1dacb.firebaseapp.com',
    storageBucket: 'yttodoapp-1dacb.firebasestorage.app',
    measurementId: 'G-PQ7SJBXJ2T',
  );
}
